# Development Environment specific config

kafka:
  brokers:
    - 192.168.1.142:9092
    - 192.168.1.143:9092
    - 192.168.1.144:9092
  consumertopic: gotest
  producertopic: gosink
  group: gogroup9